# Generated by Django 4.0.1 on 2022-03-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, max_length=1000, null=True, upload_to='avatar/%Y/%m/', verbose_name='头像')),
            ],
        ),
    ]
