# Generated by Django 4.0.1 on 2022-03-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersprofile',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='identity',
            field=models.CharField(choices=[('teacher', '教职工'), ('student', '学生'), ('tourist', '游客')], default='student', max_length=20, verbose_name='身份'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='姓名'),
        ),
    ]
