# Generated by Django 4.0.1 on 2022-03-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usersprofile_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='collection',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='收藏'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='email',
            field=models.CharField(max_length=32, null=True, verbose_name='邮箱'),
        ),
    ]
