# Generated by Django 4.0.1 on 2022-03-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usersprofile_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='email_address',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='collection',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='收藏'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱'),
        ),
    ]
