# Generated by Django 4.0.1 on 2022-03-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usersprofile_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='email',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
