# Generated by Django 4.0.1 on 2022-03-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usersprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱'),
        ),
    ]
